version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chatmosphere-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: chatmosphere
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: chatmosphere-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin@123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
