name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main, master ] # Triggers on push to main or master branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/spaces/prajwal7829/prajwal-space
          git push --force hf HEAD:main
